/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_stack`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/Paginas/Cadastro`; params?: Router.UnknownInputParams; } | { pathname: `/Paginas/Consulta`; params?: Router.UnknownInputParams; } | { pathname: `/Paginas/Dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/Paginas/Estoque`; params?: Router.UnknownInputParams; } | { pathname: `/Paginas/Pagamento`; params?: Router.UnknownInputParams; } | { pathname: `/Paginas/Vendas`; params?: Router.UnknownInputParams; } | { pathname: `/Paginas/SubPaginas/AdicionarProduto`; params?: Router.UnknownInputParams; } | { pathname: `/Paginas/SubPaginas/AtualizarFormaPagamento`; params?: Router.UnknownInputParams; } | { pathname: `/Paginas/SubPaginas/CadastroCliente`; params?: Router.UnknownInputParams; } | { pathname: `/Paginas/SubPaginas/CadastroFormaPagamento`; params?: Router.UnknownInputParams; } | { pathname: `/Paginas/SubPaginas/CadastroProduto`; params?: Router.UnknownInputParams; } | { pathname: `/Paginas/SubPaginas/ConsultaFormaPagamento`; params?: Router.UnknownInputParams; } | { pathname: `/Paginas/SubPaginas/ConsultaVendas`; params?: Router.UnknownInputParams; } | { pathname: `/Paginas/SubPaginas/ListaProdutos`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_stack`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/Paginas/Cadastro`; params?: Router.UnknownOutputParams; } | { pathname: `/Paginas/Consulta`; params?: Router.UnknownOutputParams; } | { pathname: `/Paginas/Dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/Paginas/Estoque`; params?: Router.UnknownOutputParams; } | { pathname: `/Paginas/Pagamento`; params?: Router.UnknownOutputParams; } | { pathname: `/Paginas/Vendas`; params?: Router.UnknownOutputParams; } | { pathname: `/Paginas/SubPaginas/AdicionarProduto`; params?: Router.UnknownOutputParams; } | { pathname: `/Paginas/SubPaginas/AtualizarFormaPagamento`; params?: Router.UnknownOutputParams; } | { pathname: `/Paginas/SubPaginas/CadastroCliente`; params?: Router.UnknownOutputParams; } | { pathname: `/Paginas/SubPaginas/CadastroFormaPagamento`; params?: Router.UnknownOutputParams; } | { pathname: `/Paginas/SubPaginas/CadastroProduto`; params?: Router.UnknownOutputParams; } | { pathname: `/Paginas/SubPaginas/ConsultaFormaPagamento`; params?: Router.UnknownOutputParams; } | { pathname: `/Paginas/SubPaginas/ConsultaVendas`; params?: Router.UnknownOutputParams; } | { pathname: `/Paginas/SubPaginas/ListaProdutos`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_stack${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/Paginas/Cadastro${`?${string}` | `#${string}` | ''}` | `/Paginas/Consulta${`?${string}` | `#${string}` | ''}` | `/Paginas/Dashboard${`?${string}` | `#${string}` | ''}` | `/Paginas/Estoque${`?${string}` | `#${string}` | ''}` | `/Paginas/Pagamento${`?${string}` | `#${string}` | ''}` | `/Paginas/Vendas${`?${string}` | `#${string}` | ''}` | `/Paginas/SubPaginas/AdicionarProduto${`?${string}` | `#${string}` | ''}` | `/Paginas/SubPaginas/AtualizarFormaPagamento${`?${string}` | `#${string}` | ''}` | `/Paginas/SubPaginas/CadastroCliente${`?${string}` | `#${string}` | ''}` | `/Paginas/SubPaginas/CadastroFormaPagamento${`?${string}` | `#${string}` | ''}` | `/Paginas/SubPaginas/CadastroProduto${`?${string}` | `#${string}` | ''}` | `/Paginas/SubPaginas/ConsultaFormaPagamento${`?${string}` | `#${string}` | ''}` | `/Paginas/SubPaginas/ConsultaVendas${`?${string}` | `#${string}` | ''}` | `/Paginas/SubPaginas/ListaProdutos${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_stack`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/Paginas/Cadastro`; params?: Router.UnknownInputParams; } | { pathname: `/Paginas/Consulta`; params?: Router.UnknownInputParams; } | { pathname: `/Paginas/Dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/Paginas/Estoque`; params?: Router.UnknownInputParams; } | { pathname: `/Paginas/Pagamento`; params?: Router.UnknownInputParams; } | { pathname: `/Paginas/Vendas`; params?: Router.UnknownInputParams; } | { pathname: `/Paginas/SubPaginas/AdicionarProduto`; params?: Router.UnknownInputParams; } | { pathname: `/Paginas/SubPaginas/AtualizarFormaPagamento`; params?: Router.UnknownInputParams; } | { pathname: `/Paginas/SubPaginas/CadastroCliente`; params?: Router.UnknownInputParams; } | { pathname: `/Paginas/SubPaginas/CadastroFormaPagamento`; params?: Router.UnknownInputParams; } | { pathname: `/Paginas/SubPaginas/CadastroProduto`; params?: Router.UnknownInputParams; } | { pathname: `/Paginas/SubPaginas/ConsultaFormaPagamento`; params?: Router.UnknownInputParams; } | { pathname: `/Paginas/SubPaginas/ConsultaVendas`; params?: Router.UnknownInputParams; } | { pathname: `/Paginas/SubPaginas/ListaProdutos`; params?: Router.UnknownInputParams; };
    }
  }
}
